# Generated by Django 5.1.1 on 2024-09-12 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('Endereco_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Endereco_Cep', models.CharField(max_length=10)),
                ('Endereco_Rua', models.CharField(max_length=150)),
                ('Endereco_Numero', models.CharField(max_length=10)),
                ('Endereco_Bairro', models.CharField(max_length=50)),
                ('Endereco_Cidade', models.CharField(max_length=25)),
                ('Endereco_Estado', models.CharField(max_length=20)),
                ('Endereco_Pais', models.CharField(max_length=15)),
                ('Endereco_Obs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('Medico_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Medico_Nome', models.CharField(max_length=50)),
                ('Medico_CRM', models.CharField(max_length=10)),
                ('Medico_Especialidade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('Local_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Local_Nome', models.CharField(max_length=50)),
                ('Local_Tipo', models.CharField(max_length=10)),
                ('Local_HoraInicio', models.DateTimeField()),
                ('Local_HoraFim', models.DateTimeField()),
                ('Local_Endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('Doacao_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Doacao_Data', models.DateField()),
                ('Doacao_Local', models.ManyToManyField(to='telas.local')),
            ],
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('Checkup_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Checkup_Cid', models.CharField(max_length=10)),
                ('Checkup_Obs', models.CharField(max_length=100)),
                ('Checkup_Data', models.DateField()),
                ('Checkup_Medico', models.ManyToManyField(to='telas.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('Pessoa_Cpf', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Pessoa_Nome', models.CharField(max_length=50)),
                ('Pessoa_Telefone1', models.CharField(max_length=15)),
                ('Pessoa_Telefone2', models.CharField(blank=True, max_length=15, null=True)),
                ('Pessoa_Peso', models.FloatField()),
                ('Pessoa_Altura', models.CharField(max_length=5)),
                ('Pessoa_TipoSanguineo', models.CharField(max_length=3)),
                ('Pessoa_Sexo', models.CharField(max_length=1)),
                ('Pessoa_DataNascimento', models.DateField()),
                ('Pessoa_Checkup', models.ManyToManyField(blank=True, to='telas.checkup')),
                ('Pessoa_Doacoes', models.ManyToManyField(blank=True, to='telas.doacao')),
                ('Pessoa_Endereco', models.ManyToManyField(blank=True, to='telas.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Compartilhamento',
            fields=[
                ('Compartilhamento_Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Compartilhamento_Data', models.DateField()),
                ('Compartilhamento_Link', models.URLField()),
                ('Compartilhamento_Doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas.doacao')),
                ('Compartilhamento_Local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas.local')),
                ('Compartilhamento_Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas.pessoa')),
            ],
        ),
    ]
