# Generated by Django 5.1.1 on 2024-09-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='Pessoa_Checkup',
            field=models.ManyToManyField(to='telas.checkup'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='Pessoa_Doacoes',
            field=models.ManyToManyField(to='telas.doacao'),
        ),
    ]
