# Generated by Django 5.1.1 on 2024-09-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0002_alter_pessoa_pessoa_checkup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='Pessoa_Endereco',
            field=models.ManyToManyField(to='telas.endereco'),
        ),
    ]
