# Generated by Django 5.1.1 on 2024-09-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0003_alter_pessoa_pessoa_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='Pessoa_DataNascimento',
            field=models.CharField(max_length=15),
        ),
    ]
